language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

env:
  - BABEL=true

matrix:
  exclude:
    - node_js: "6"
      env: "babel=true"

script: "[[ $BABEL == true ]] && npm run test:babel || npm test"
after_success:
  - npm run travis-coverage
